name: re7_pratica
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  responsive_framework: ^0.1.9
  flutter_svg: ^1.0.3
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  mask_text_input_formatter: ^2.3.0
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  dio: ^4.0.6
  path_provider: ^2.0.10
  open_file: ^3.2.1
  url_launcher: ^6.1.2
  path: ^1.8.0
  image_picker: ^0.8.5+3
  file_picker: ^4.6.1
  grouped_list: ^5.1.2
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  youtube_player_flutter: ^8.1.2
  audio_session: ^0.1.13
  lottie: ^2.2.0
  flutter_animate: ^4.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - lottie/
    - assets/
    - assets/images/
    - assets/icons/
    - .env.development
    - .env.production
